FROM python:3.11

WORKDIR /app

# Copy requirements first for caching
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy only necessary files
COPY northwind.db .
COPY server.py .
COPY neo4j_setup.py .
COPY user_query_runner.py .

EXPOSE 8000

# Run FastAPI server
CMD ["gunicorn", "server:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--timeout", "1200"]